apiVersion: v1
kind: Service
metadata:
  name: tracing-api
spec:
  selector:
    app: tracing-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 3000

